### ISSUE TITLE
host_vars dir instead of hosts_vars

### ISSUE THREAD

**Issue by refraction-ray** [Linaro/ansible-playbook-for-ohpc#18]
The name convention and search path for variables should be `host_vars` instead of `hosts_vars`. Though there is nothing to configure in the default scenario, it would be better to fix the typo.

**Comment by BaptisteGerondeau** [comment]
Sorry for the late answer, and thanks for the tip !
Fixed by 5794719e5db6b909d38068f9e75996f4ffd45342
